### ISSUE TITLE
Support voor .PPTX bestanden

### ISSUE THREAD

**Issue by KoenvanMeijeren** [Mart-0/ELO#2]
Vraagje, is het mogelijk om support in te bouwen voor het lezen van .PPTX bestanden?

Ik merk dat ik het vervelend vindt om eerst de powerpoint te downloaden voordat je het bestand kan bekijken. Ik weet niet of het mogelijk is maar het zou mn leven wel wat makkelijker maken als powerpoints bekeken konden worden vanuit de browser.

**Comment by Mart-0** [comment]
Is een goeie vraag,

PowerPoint, Word, Excel bestanden kunnen niet direct in de browser geopend worden. De PowerPoint zouden omgezet kunnen worden naar een pdf-bestand. Het liefst zou ik die bestanden willen omzetten in de client, zover ik weet zijn er geen tools die de PowerPoint om kunnen zetten zonder te veel styling te verliezen.
De oplossing zou zijn om een server op te zetten waar alle documenten worden omgezet naar pdf. Zodat het vervolgens goed getoond kan worden.

Ik had gekozen om dit geen prioriteit te maken vanwege de veiligheid en het onderhoud van een server.

**Comment by KoenvanMeijeren** [comment]
Begrijpelijk, het kostte mij ook erg veel moeite om Word bestanden om te zetten naar pdf. Uiteindelijk heb ik het gedaan via LibreOffice maar dat werd serverside afgehandeld. 

Voor nu dus niet. Toch bedankt voor de moeite.

Ps: .MD bestanden zou wel relatief makkelijk kunnen, maar ik weet niet hoe vaak die bestanden voorkomen..
